### ISSUE TITLE
`jwks.json` is not a well-known URI

### ISSUE THREAD

**Issue by bellebaum** [oxisto/oauth2go#45]
Compare to https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

There is probably no harm in placing it there either, but the standards police might not like this...

**Comment by oxisto** [comment]
It seems to be "well used", for example:
- https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets
- https://docs.cidaas.com/standard-endpoints/server-jwk-set.html#31-well-knownjwksjson

I am up to suggestions where to put it :)

**Comment by bellebaum** [comment]
If you want it to be found automagically, I think the best way to do that is to implement [RFC 8414](https://datatracker.ietf.org/doc/rfc8414/) and advertise it as `jwks_uri` :)

[Omejdn](https://github.com/Fraunhofer-AISEC/omejdn-server) recently moved it to just `/jwks.json`
But any place is fine, e.g.

- https://www.googleapis.com/oauth2/v3/certs
- https://api.paypal.com/v1/oauth2/certs
- https://login.microsoftonline.com/775527ff-9a37-4307-8b3d-cc311f58d925/discovery/v2.0/keys
- https://www.facebook.com/.well-known/oauth/openid/jwks/ (:angry:, but they don't even get RFC 8414 correct)
